# Generated by Django 3.2 on 2021-04-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20210423_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='participants',
            new_name='participents',
        ),
    ]
