# Generated by Django 3.2 on 2021-04-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_rename_participants_podcast_participents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
